### ISSUE TITLE
Make the buttons <button> elements

### ISSUE THREAD

**Issue by travellingprog** [fengxia41103/sp500#1]
Hey Feng,

Cool project! Quick tip, you should make change these `<span>` to `<button>` elements: https://github.com/fengxia41103/sp500/blob/6607664bcdf9ba28985873e5ec4f571fbb7b759d/src/index.jsx#L140

For some reason, when I over over these spans, I get the "text edit" mouse cursor. Switching it to a button should fix that. Anyways, thanks for sharing your work.

**Comment by fengxia41103** [comment]
Fixed in commit 6af6376

**Comment by fengxia41103** [comment]
See above.
